import type Logger from "@dockstat/logger"
import type { QueryBuilder } from "@dockstat/sqlite-wrapper"
import Elysia, { t } from "elysia"
import * as client from "openid-client"
import type { ConfigService } from "./config"
import type { LocalUsersTable, ProvidersTable } from "./types"
import crypt from "./utils/encrypt"
import { BASE_URL, FRONTEND_URL } from "./utils/env"
import { createAuthToken } from "./utils/jwt"

export function createAuthRoutes(
  table: QueryBuilder<ProvidersTable>,
  users: QueryBuilder<LocalUsersTable>,
  logger: Logger,
  configService: ConfigService
) {
  return new Elysia({ detail: { tags: ["Auth"] }, prefix: "/auth" })
    .post(
      "/providers",
      async ({ body }) =>
        table.insertAndGet({
          ...(body as object),
          client_secret: await crypt.encrypt((body as { client_secret: string }).client_secret),
          scopes: (body as { scopes: string }).scopes ? (body as { scopes: string }).scopes : null,
        }),
      {
        body: t.Object({
          client_id: t.String(),
          client_secret: t.String(),
          issuer_url: t.String(),
          logout_url: t.MaybeEmpty(t.String()),
          scopes: t.MaybeEmpty(t.String()),
        }),
        detail: {
          description: "Create a new OAuth/OIDC provider",
          summary: "Create Provider",
        },
      }
    )
    .get(
      "/:providerId/login",
      async ({ params: { providerId }, redirect, cookie: { state, nonce, pkce } }) => {
        const { meta, scopes } = await configService.getConfig(providerId)

        const stateVal = client.randomState()
        const nonceVal = client.randomNonce()

        const code_verifier = client.randomPKCECodeVerifier()
        const code_challenge = await client.calculatePKCECodeChallenge(code_verifier)

        const isSecure = BASE_URL.startsWith("https://")
        logger.info(`Setting OAuth cookies for provider ${providerId} (secure: ${isSecure})`)

        state.value = stateVal
        state.httpOnly = true
        state.secure = isSecure
        state.sameSite = "lax"
        state.maxAge = 600

        nonce.value = nonceVal
        nonce.httpOnly = true
        nonce.secure = isSecure
        nonce.sameSite = "lax"
        nonce.maxAge = 600

        pkce.value = code_verifier
        pkce.httpOnly = true
        pkce.secure = isSecure
        pkce.sameSite = "lax"
        pkce.maxAge = 600

        const params: Record<string, string> = {
          code_challenge,
          code_challenge_method: "S256",
          nonce: nonceVal,
          redirect_uri: `${BASE_URL}/${providerId}/callback`,
          scopes,
          state: stateVal,
        }

        const redirectTo: URL = client.buildAuthorizationUrl(meta, params)

        logger.info(`=== OAuth Login Flow ===`)
        logger.info(`Authorization URL: ${redirectTo.toString()}`)
        logger.info(`Params sent: ${JSON.stringify(params)}`)
        logger.info(`=== End Login Flow ===\n`)
        return redirect(redirectTo.toString())
      },
      {
        detail: {
          description: "Login using the autogenerated ID (from the DB) of the Provider",
          summary: "Login",
        },
        params: t.Object({ providerId: t.String() }),
      }
    )
    .get(
      "/:providerId/callback",
      async ({ params: { providerId }, query, cookie, set, redirect }) => {
        const { meta } = await configService.getConfig(providerId)
        const { state: returnedState, code } = query

        logger.info(`=== OAuth Callback Flow for ${providerId} ===`)
        logger.info(`Query params: ${JSON.stringify(query)}`)
        logger.info(`Code present: ${!!code}`)
        logger.info(`Returned state: ${returnedState}`)

        // Check if OAuth cookies are present (they should have been set by login route)
        if (!cookie.state?.value || !cookie.nonce?.value || !cookie.pkce?.value) {
          logger.error(
            `Missing OAuth cookies - login route may have failed ${JSON.stringify({
              allCookies: Object.keys(cookie),
              nonce: cookie.nonce?.value ? "present" : "missing",
              pkce: cookie.pkce?.value ? "present" : "missing",
              state: cookie.state?.value ? "present" : "missing",
            })}`
          )
          set.status = 400
          return "Authentication failed: Missing security cookies. Please try logging in again from the login page."
        }

        logger.info(`Cookie state: ${cookie.state.value}`)
        logger.info(`Cookie nonce: ${cookie.nonce.value}`)
        logger.info(`Cookie pkce: ${String(cookie.pkce.value).substring(0, 20)}...`)

        if (cookie.state.value !== returnedState) {
          logger.error(
            `Invalid state parameter in OAuth callback: ${JSON.stringify({
              expected: cookie.state.value,
              received: returnedState,
            })}`
          )
          set.status = 400
          return "Invalid state"
        }

        logger.info("State validation passed. Exchanging authorization code for tokens...")

        const callbackUrl = new URL(
          `${BASE_URL}/${providerId}/callback?${new URLSearchParams(query)}`
        )
        logger.info(`Callback URL for token exchange: ${callbackUrl.toString()}`)

        // Log detailed token exchange parameters
        const serverMetadata = meta.serverMetadata()
        logger.info(`=== Token Exchange Parameters ===`)
        logger.info(`Token Endpoint: ${serverMetadata.token_endpoint}`)
        logger.info(`Authorization Endpoint: ${serverMetadata.authorization_endpoint}`)
        logger.info(`Expected Nonce: ${cookie.nonce.value}`)
        logger.info(`Expected State: ${cookie.state.value}`)
        logger.info(
          `PKCE Code Verifier (first 20 chars): ${String(cookie.pkce.value).substring(0, 20)}...`
        )
        logger.info(`Full PKCE Code Verifier: ${String(cookie.pkce.value)}`)
        logger.info(`Callback URL (full): ${callbackUrl.toString()}`)
        logger.info(`=== End Token Exchange Parameters ===`)

        try {
          const tokens = await client.authorizationCodeGrant(meta, callbackUrl, {
            expectedNonce: String(cookie.nonce.value),
            expectedState: String(cookie.state.value),
            pkceCodeVerifier: String(cookie.pkce.value),
          })
          logger.info(`Token exchange successful! Token type: ${tokens.token_type}`)

          const userInfo = await client.fetchUserInfo(
            meta,
            tokens.access_token,
            String(tokens.claims().sub)
          )
          logger.info(`Successfully fetched user info for: ${userInfo.email || userInfo.sub}`)

          cookie.state.remove()
          cookie.nonce.remove()
          cookie.pkce.remove()

          // Create a JWT with user info to pass to the frontend
          const token = await createAuthToken(userInfo)

          // Redirect to frontend callback page with JWT token
          const frontendCallbackUrl = `${FRONTEND_URL}/auth/${providerId}/callback?token=${token}`
          logger.info(
            `Redirecting to frontend callback: ${FRONTEND_URL}/auth/${providerId}/callback`
          )

          return redirect(frontendCallbackUrl)
        } catch (error) {
          const errorDetails = {
            constructor: error?.constructor?.name,
            error: error instanceof Error ? error.message : String(error),
            name: error instanceof Error ? error.name : undefined,
            stack: error instanceof Error ? error.stack : undefined,
          }

          logger.error(`Token exchange failed! ${JSON.stringify(errorDetails, null, 2)}`)
          set.status = 500
          return `Authentication failed: ${error instanceof Error ? error.message : "Unknown error"}`
        }
      },
      {
        detail: {
          description: "Sets the cookie values and redirects to the frontend",
          summary: "Callback",
        },
        params: t.Object({ providerId: t.String() }),
        query: t.Object({ code: t.String(), state: t.String() }),
      }
    )
    .get(
      "/providers",
      () => table.select(["id", "issuer_url", "scopes", "client_id", "created_at"]).all(),
      {
        detail: {
          description: "Lists all Providers",
          summary: "All Providers",
        },
      }
    )
    .get(
      "/:providerId/logout",
      async ({ params: { providerId }, query, redirect }) => {
        const { meta } = await configService.getConfig(providerId)
        const { logout_url: logoutUrl } = table
          .select(["logout_url"])
          .where({ id: providerId })
          .first()

        logger.info(`Logging out from ${providerId}; redirect after: ${query.redirectUri}`)

        let redirectTo = client.buildEndSessionUrl(meta, {
          post_logout_redirect_uri: query.redirectUri,
        })

        if (logoutUrl !== null) {
          redirectTo = new URL(logoutUrl)
        }

        logger.info(`End Session URL: ${redirectTo.toString()}`)

        return redirect(redirectTo.toString())
      },
      {
        detail: {
          description:
            "Logout of the Provider which matches the Provider ID from the DB. If a logout_url is defined for the Provider it will use that, otherwise build it from the OIDC-Metadata of the provider",
          summary: "Logout",
        },
        params: t.Object({ providerId: t.String() }),
        query: t.Object({ redirectUri: t.String() }),
      }
    )
    .group("/local", (app) =>
      app
        .post(
          "/register",
          async ({ body, set }) => {
            try {
              const requestBody = body as { name: string; pass: string }

              // Check if user already exists
              const existingUser = users.select(["id"]).where({ name: requestBody.name }).first()

              if (existingUser) {
                set.status = 409
                return { error: "Username already exists" }
              }

              // Hash password with argon2id
              const passHash = await Bun.password.hash(requestBody.pass, {
                algorithm: "argon2id",
                memoryCost: 65536,
                timeCost: 4,
              })

              // Create user
              const user = await users.insertAndGet({
                name: requestBody.name,
                passHash,
              })

              logger.info(`New local user registered: ${requestBody.name}`)

              return {
                success: true,
                user: { id: user.id, name: user.name },
              }
            } catch (error) {
              const requestBody = body as { name: string; pass: string }
              logger.error(`Registration failed for ${requestBody.name}: ${error}`)
              set.status = 500
              return { error: "Registration failed" }
            }
          },
          {
            body: t.Object({
              name: t.String({ maxLength: 50, minLength: 3 }),
              pass: t.String({ minLength: 8 }),
            }),
            detail: {
              description: "Register a new local user",
              summary: "Register",
            },
          }
        )
        .get(
          "/login",
          async ({ redirect }) => {
            const loginUrl = `${FRONTEND_URL}/auth/local/login`
            logger.info(`Redirecting to local login page: ${loginUrl}`)
            return redirect(loginUrl)
          },
          {
            detail: {
              description: "Redirect to frontend login page",
              summary: "Login Page",
            },
          }
        )
        .post(
          "/login",
          async ({ body, set, redirect }) => {
            try {
              const requestBody = body as { name: string; pass: string }

              // Find user by username
              const user = users
                .select(["id", "name", "passHash"])
                .where({ name: requestBody.name })
                .first()

              if (!user) {
                logger.warn(`Login attempt for non-existent user: ${requestBody.name}`)
                set.status = 401
                return { error: "Invalid credentials" }
              }

              // Verify password
              const isValid = await Bun.password.verify(requestBody.pass, user.passHash)

              if (!isValid) {
                logger.warn(`Failed login attempt for user: ${requestBody.name}`)
                set.status = 401
                return { error: "Invalid credentials" }
              }

              logger.info(`Successful login for local user: ${requestBody.name}`)

              // Create JWT token with user info
              const token = await createAuthToken({
                email: user.name,
                name: user.name,
                provider: "local",
                sub: user.id,
              })

              // Return token to frontend (avoid CORS issues with redirect from POST)
              return {
                success: true,
                token,
              }
            } catch (error) {
              const requestBody = body as { name: string; pass: string }
              logger.error(`Login failed for ${requestBody.name}: ${error}`)
              set.status = 500
              return { error: "Login failed" }
            }
          },
          {
            body: t.Object({
              name: t.String(),
              pass: t.String(),
            }),
            detail: {
              description: "Authenticate with username and password",
              summary: "Login",
            },
          }
        )
        .get(
          "/logout",
          async ({ query, redirect }) => {
            const redirectUri = query.redirectUri || FRONTEND_URL
            logger.info(`Local user logout, redirecting to: ${redirectUri}`)
            return redirect(redirectUri)
          },
          {
            detail: {
              description: "Logout local user and redirect",
              summary: "Logout",
            },
            query: t.Object({
              redirectUri: t.Optional(t.String()),
            }),
          }
        )
        .get(
          "/exists",
          async () => {
            try {
              const user = users.select(["id"]).first()
              const exists = !!user
              logger.info(`Local user exists check: ${exists}`)
              return { exists }
            } catch (error) {
              logger.error(`Error checking if local user exists: ${error}`)
              return { exists: false }
            }
          },
          {
            detail: {
              description: "Check if any local users exist",
              summary: "Check Local Users",
            },
          }
        )
    )
}
