name: Dockstat App Issue
description: Report an issue specific to the Dockstat application
title: "[DOCKSTAT] "
labels: ["dockstat", "app", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with the Dockstat app! This template is specifically for issues related to the Dockstat Docker statistics application.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug - Something isn't working correctly
        - Performance - Slow or resource-intensive behavior
        - UI/UX - User interface or experience issue
        - Data Display - Incorrect or missing statistics
        - Docker Integration - Issues with Docker API or containers
        - Feature Request - New functionality for Dockstat
        - Configuration - Setup or configuration problems
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a clear and detailed description of the issue
      placeholder: Describe what's happening and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: docker-environment
    attributes:
      label: Docker Environment
      description: Information about your Docker setup
      value: |
        - Docker version: [e.g. 24.0.6]
        - Docker Compose version: [e.g. 2.21.0] (if applicable)
        - Number of containers: [e.g. 15]
        - Container types: [e.g. web servers, databases, microservices]
        - Docker host: [e.g. local, remote, Docker Desktop]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Start Dockstat app
        2. Navigate to...
        3. Perform action...
        4. Observe issue
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual Behavior
      description: What did you expect to happen vs what actually happened?
      value: |
        **Expected:**

        **Actual:**
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Information about your system
      value: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node.js version: [e.g. 18.17.0]
        - Bun version: [e.g. 1.0.0]
        - Browser: [e.g. Chrome 118, Safari 17] (if web-based)
        - Dockstat version: [e.g. 1.0.0]
    validations:
      required: true

  - type: textarea
    id: container-details
    attributes:
      label: Affected Container Details
      description: If the issue relates to specific containers, provide details
      placeholder: |
        Container names, images, resource usage, states, etc.
      render: text

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant log output from Dockstat or Docker
      placeholder: Paste logs here (Docker logs, Dockstat logs, browser console, etc.)
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the issue
      placeholder: Drag and drop images or paste URLs

  - type: dropdown
    id: frequency
    attributes:
      label: Issue Frequency
      description: How often does this issue occur?
      options:
        - Always - Every time I try
        - Often - Most of the time
        - Sometimes - Occasionally
        - Rarely - Once or twice
        - Unknown - Not sure
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any temporary workarounds for this issue?
      placeholder: If you've found a way to work around this issue, please describe it

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that might be helpful
      placeholder: Network configuration, firewall settings, other Docker tools used, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information above
          required: true
        - label: This issue is specifically related to the Dockstat app
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
