name: Docs App Issue
description: Report an issue specific to the Documentation application
title: "[DOCS] "
labels: ["docs", "app", "documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with the Docs app! This template is specifically for issues related to the documentation site and its content.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug - Something isn't working correctly
        - Content - Incorrect, outdated, or missing documentation
        - UI/UX - User interface or experience issue
        - Navigation - Issues with site navigation or structure
        - Search - Problems with documentation search functionality
        - Performance - Slow loading or rendering issues
        - Accessibility - Issues with screen readers or accessibility features
        - Mobile - Issues on mobile devices or responsive design
        - Feature Request - New functionality for the docs site
        - Broken Links - Links that don't work or point to wrong content
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a clear and detailed description of the issue
      placeholder: Describe what's wrong with the documentation or docs site
    validations:
      required: true

  - type: textarea
    id: page-url
    attributes:
      label: Page URL or Section
      description: Which page or section of the docs is affected?
      placeholder: |
        - URL: https://docs.example.com/path/to/page
        - Section: Getting Started > Installation
        - Component: API Reference > SQLite Wrapper
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to documentation page...
        2. Navigate to section...
        3. Try to follow instructions...
        4. Observe issue
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual Behavior
      description: What did you expect to see vs what actually happened?
      value: |
        **Expected:**

        **Actual:**
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Information about your system and browser
      value: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Browser: [e.g. Chrome 118, Safari 17, Firefox 119]
        - Screen size: [e.g. Desktop 1920x1080, Mobile 375x812]
        - Device type: [e.g. Desktop, Tablet, Mobile]
    validations:
      required: true

  - type: textarea
    id: content-suggestions
    attributes:
      label: Content Suggestions
      description: If this is a content issue, what should the correct information be?
      placeholder: |
        Provide the correct information, links to authoritative sources, or suggestions for improvement
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the issue
      placeholder: Drag and drop images or paste URLs

  - type: dropdown
    id: priority
    attributes:
      label: Impact Level
      description: How much does this issue impact documentation users?
      options:
        - Low - Minor typo or cosmetic issue
        - Medium - Confusing content or broken feature
        - High - Incorrect information that could cause problems
        - Critical - Completely wrong or missing critical information
    validations:
      required: true

  - type: textarea
    id: user-context
    attributes:
      label: User Context
      description: What were you trying to accomplish when you encountered this issue?
      placeholder: I was trying to learn how to... / I was looking for information about...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that might be helpful
      placeholder: Related documentation sections, external resources, version information, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information above
          required: true
        - label: This issue is specifically related to the documentation site
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
