name: Typings Package Issue
description: Report an issue specific to the Typings package
title: "[TYPINGS] "
labels: ["typings", "package", "typescript", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with the Typings package! This template is specifically for issues related to the shared TypeScript type definitions and interfaces.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug - Something isn't working correctly
        - Type Safety - TypeScript type issues or inference problems
        - Missing Types - Types that should exist but don't
        - Incorrect Types - Types that don't match actual implementation
        - Breaking Changes - Types that break existing code
        - Documentation - Type documentation or JSDoc issues
        - Export Issues - Problems with type exports or imports
        - Generic Constraints - Issues with generic type constraints
        - Utility Types - Problems with utility or helper types
        - Feature Request - New types or interfaces needed
        - Compatibility - Issues with TypeScript versions
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a clear and detailed description of the issue
      placeholder: Describe what's wrong with the types or what types are needed
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Provide a minimal code example that demonstrates the issue
      placeholder: |
        ```typescript
        import { SomeType } from '@dockstat/typings';

        // Your code that demonstrates the type issue
        const example: SomeType = {
          // ...
        };
        ```
      render: typescript
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual Type Behavior
      description: What types did you expect vs what actually happened?
      value: |
        **Expected Types:**

        **Actual Types:**

        **TypeScript Error (if any):**
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your TypeScript environment
      value: |
        - Package version: [e.g. 1.0.0]
        - TypeScript version: [e.g. 5.2.0]
        - Runtime: [e.g. Bun 1.0.0, Node.js 18.17.0]
        - IDE/Editor: [e.g. VSCode 1.85.0, WebStorm 2023.3]
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - tsconfig.json strict mode: [e.g. enabled/disabled]
    validations:
      required: true

  - type: textarea
    id: type-definition
    attributes:
      label: Current Type Definition
      description: If reporting an issue with existing types, show the current definition
      placeholder: |
        ```typescript
        // Current type definition from the package
        export interface ExampleType {
          // ...
        }
        ```
      render: typescript

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Type Solution
      description: If you have ideas for how the types should be defined, provide them here
      placeholder: |
        ```typescript
        // Proposed type definition
        export interface ExampleType {
          // ...
        }
        ```
      render: typescript

  - type: textarea
    id: typescript-error
    attributes:
      label: TypeScript Error Output
      description: Include any TypeScript compiler errors or IDE type errors
      placeholder: Paste the complete TypeScript error messages here
      render: text

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you're trying to use these types and what you're building
      placeholder: I'm trying to build... and I need types for...
    validations:
      required: true

  - type: dropdown
    id: affected-areas
    attributes:
      label: Affected Type Areas
      description: Which areas of the typings package are affected?
      multiple: true
      options:
        - Database types
        - Theme types
        - Archive types
        - Utility types
        - API response types
        - Configuration types
        - Event types
        - Component types
        - Other

  - type: dropdown
    id: severity
    attributes:
      label: Impact Severity
      description: How severely does this issue impact your development?
      options:
        - Low - Minor inconvenience, workaround available
        - Medium - Affects type safety or development experience
        - High - Blocks development or causes runtime issues
        - Critical - Completely prevents usage
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: Have you found any temporary workarounds for this type issue?
      placeholder: |
        ```typescript
        // Current workaround (if any)
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that might be helpful
      placeholder: Related types, external libraries used, migration concerns, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal code example that demonstrates the issue
          required: true
        - label: I have included my TypeScript version and configuration
          required: true
        - label: This issue is specifically related to the Typings package
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
