// @generated by .server/scripts/index.ts — do not edit
import { clientAction } from "~/lib/api"
import type { Schemas } from "~/.server/schemas"

/**
 * Fully-typed API client generated from the server Schemas registry.
 *
 *   executeAction["Auth.ApiKey.revoke"]({ params: { id: "abc" } })
 *   executeAction["Config.Pin.pin"]({ body: { path, slug } })
 *
 * Schemas is imported type-only: types flow from the server registry while
 * the client bundle only contains the clientAction runtime.
 */
export const executeAction = {
	"Auth.ApiKey.revoke": clientAction<
		typeof Schemas.Auth.ApiKey["_ops"],
		"revoke",
		"auth/api-keys/:id"
	>("revoke", "auth/api-keys/:id"),
	"Auth.Guest.toggle": clientAction<
		typeof Schemas.Auth.Guest["_ops"],
		"toggle",
		"auth/guest/:allow"
	>("toggle", "auth/guest/:allow"),
	"Auth.LocalLogin.login": clientAction<
		typeof Schemas.Auth.LocalLogin["_ops"],
		"login",
		"auth/local/login"
	>("login", "auth/local/login"),
	"Auth.LocalRegister.register": clientAction<
		typeof Schemas.Auth.LocalRegister["_ops"],
		"register",
		"auth/local/register"
	>("register", "auth/local/register"),
	"Auth.Provider.delete": clientAction<
		typeof Schemas.Auth.Provider["_ops"],
		"delete",
		"auth/providers/:providerId"
	>("delete", "auth/providers/:providerId"),
	"Auth.Providers.create": clientAction<
		typeof Schemas.Auth.Providers["_ops"],
		"create",
		"auth/providers"
	>("create", "auth/providers"),
	"Auth.Revoke.revoke": clientAction<
		typeof Schemas.Auth.Revoke["_ops"],
		"revoke",
		"auth/revoke"
	>("revoke", "auth/revoke"),
	"Auth.User.delete": clientAction<
		typeof Schemas.Auth.User["_ops"],
		"delete",
		"auth/users/:userId"
	>("delete", "auth/users/:userId"),
	"Config.Pin.pin": clientAction<
		typeof Schemas.Config.Pin["_ops"],
		"pin",
		"config/pin"
	>("pin", "config/pin"),
	"Config.Pin.unpin": clientAction<
		typeof Schemas.Config.Pin["_ops"],
		"unpin",
		"config/pin"
	>("unpin", "config/pin"),
}
