import type { Config } from 'tailwindcss'
export default {
  theme: {
    extend: {
      colors: {
        'badge-default-bg': 'var(--theme-components-badge-default-bg)',
        'badge-default-color': 'var(--theme-components-badge-default-color)',
        'badge-error-bg': 'var(--theme-components-badge-error-bg)',
        'badge-error-color': 'var(--theme-components-badge-error-color)',
        'badge-success-bg': 'var(--theme-components-badge-success-bg)',
        'badge-success-color': 'var(--theme-components-badge-success-color)',
        'badge-warning-bg': 'var(--theme-components-badge-warning-bg)',
        'badge-warning-color': 'var(--theme-components-badge-warning-color)',
        'button-primary-bg': 'var(--theme-components-button-primary-bg)',
        'button-primary-color': 'var(--theme-components-button-primary-color)',
        'button-primary-hover-bg':
          'var(--theme-components-button-primary-hover-bg)',
        'button-secondary-bg': 'var(--theme-components-button-secondary-bg)',
        'button-secondary-color':
          'var(--theme-components-button-secondary-color)',
        'button-secondary-hover-bg':
          'var(--theme-components-button-secondary-hover-bg)',
        'card-bg': 'var(--theme-components-card-bg)',
        'card-content-font-color':
          'var(--theme-components-card-content-font-color)',
        'chart-axis-color': 'var(--theme-components-chart-axis-color)',
        'chart-bar-color': 'var(--theme-components-chart-bar-color)',
        'chart-bg': 'var(--theme-components-chart-bg)',
        'chart-grid-color': 'var(--theme-components-chart-grid-color)',
        'chart-label-color': 'var(--theme-components-chart-label-color)',
        'chart-title-color': 'var(--theme-components-chart-title-color)',
        'chart-title-font-size':
          'var(--theme-components-chart-title-font-size)',
        'chart-tooltip-bg': 'var(--theme-components-chart-tooltip-bg)',
        'chart-tooltip-color': 'var(--theme-components-chart-tooltip-color)',
        'dialog-bg': 'var(--theme-components-dialog-bg)',
        'dialog-overlay-bg': 'var(--theme-components-dialog-overlay-bg)',
        'dropdown-bg': 'var(--theme-components-dropdown-bg)',
        'dropdown-item-hover-bg':
          'var(--theme-components-dropdown-item-hover-bg)',
        'dropdown-item-hover-color':
          'var(--theme-components-dropdown-item-hover-color)',
        'hovercard-bg': 'var(--theme-components-hovercard-bg)',
        'input-bg': 'var(--theme-components-input-bg)',
        'input-color': 'var(--theme-components-input-color)',
        'progress-bar-bg': 'var(--theme-components-progress-bar-bg)',
        'progress-bg': 'var(--theme-components-progress-bg)',
        'sonner-bg': 'var(--theme-components-sonner-bg)',
        'sonner-button-bg': 'var(--theme-components-sonner-button-bg)',
        'sonner-button-color': 'var(--theme-components-sonner-button-color)',
        'sonner-cancel-bg': 'var(--theme-components-sonner-cancel-bg)',
        'sonner-cancel-color': 'var(--theme-components-sonner-cancel-color)',
        'sonner-close-bg': 'var(--theme-components-sonner-close-bg)',
        'sonner-close-color': 'var(--theme-components-sonner-close-color)',
        'sonner-color': 'var(--theme-components-sonner-color)',
        'sonner-error-bg': 'var(--theme-components-sonner-error-bg)',
        'sonner-error-border': 'var(--theme-components-sonner-error-border)',
        'sonner-error-color': 'var(--theme-components-sonner-error-color)',
        'sonner-info-bg': 'var(--theme-components-sonner-info-bg)',
        'sonner-info-border': 'var(--theme-components-sonner-info-border)',
        'sonner-info-color': 'var(--theme-components-sonner-info-color)',
        'sonner-loading-bg': 'var(--theme-components-sonner-loading-bg)',
        'sonner-loading-color': 'var(--theme-components-sonner-loading-color)',
        'sonner-success-bg': 'var(--theme-components-sonner-success-bg)',
        'sonner-success-border':
          'var(--theme-components-sonner-success-border)',
        'sonner-success-color': 'var(--theme-components-sonner-success-color)',
        'sonner-title-font-size':
          'var(--theme-components-sonner-title-font-size)',
        'sonner-warning-bg': 'var(--theme-components-sonner-warning-bg)',
        'sonner-warning-border':
          'var(--theme-components-sonner-warning-border)',
        'sonner-warning-color': 'var(--theme-components-sonner-warning-color)',
        'switch-bg': 'var(--theme-components-switch-bg)',
        'switch-enabled-bg': 'var(--theme-components-switch-enabled-bg)',
        'switch-thumb-bg': 'var(--theme-components-switch-thumb-bg)',
        'switch-thumb-enabled-transform':
          'var(--theme-components-switch-thumb-enabled-transform)',
        'table-body-bg': 'var(--theme-components-table-body-bg)',
        'table-header-bg': 'var(--theme-components-table-header-bg)',
        'textarea-bg': 'var(--theme-components-textarea-bg)',
        'textarea-color': 'var(--theme-components-textarea-color)',
      },
      spacing: {
        'badge-padding-x': 'var(--theme-components-badge-padding-x)',
        'badge-padding-y': 'var(--theme-components-badge-padding-y)',
        'button-padding-x': 'var(--theme-components-button-padding-x)',
        'button-padding-y': 'var(--theme-components-button-padding-y)',
        'card-footer-padding': 'var(--theme-components-card-footer-padding)',
        'card-header-padding': 'var(--theme-components-card-header-padding)',
        'card-padding': 'var(--theme-components-card-padding)',
        'chart-padding': 'var(--theme-components-chart-padding)',
        'dialog-padding': 'var(--theme-components-dialog-padding)',
        'hovercard-padding': 'var(--theme-components-hovercard-padding)',
        'input-padding-x': 'var(--theme-components-input-padding-x)',
        'input-padding-y': 'var(--theme-components-input-padding-y)',
        'table-cell-padding-x': 'var(--theme-components-table-cell-padding-x)',
        'table-cell-padding-y': 'var(--theme-components-table-cell-padding-y)',
        'textarea-padding-x': 'var(--theme-components-textarea-padding-x)',
        'textarea-padding-y': 'var(--theme-components-textarea-padding-y)',
      },
      fontSize: {
        'badge-font-size': 'var(--theme-components-badge-font-size)',
        'button-font-size': 'var(--theme-components-button-font-size)',
        'card-content-font-size':
          'var(--theme-components-card-content-font-size)',
        'input-font-size': 'var(--theme-components-input-font-size)',
        'sonner-button-font-size':
          'var(--theme-components-sonner-button-font-size)',
        'sonner-description-font-size':
          'var(--theme-components-sonner-description-font-size)',
        'table-cell-font-size': 'var(--theme-components-table-cell-font-size)',
        'textarea-font-size': 'var(--theme-components-textarea-font-size)',
      },
      borderRadius: {
        'badge-radius': 'var(--theme-components-badge-radius)',
        'button-radius': 'var(--theme-components-button-radius)',
        'card-radius': 'var(--theme-components-card-radius)',
        'chart-radius': 'var(--theme-components-chart-radius)',
        'chart-tooltip-radius': 'var(--theme-components-chart-tooltip-radius)',
        'dialog-radius': 'var(--theme-components-dialog-radius)',
        'dropdown-radius': 'var(--theme-components-dropdown-radius)',
        'hovercard-radius': 'var(--theme-components-hovercard-radius)',
        'input-radius': 'var(--theme-components-input-radius)',
        'progress-radius': 'var(--theme-components-progress-radius)',
        'switch-radius': 'var(--theme-components-switch-radius)',
        'switch-thumb-radius': 'var(--theme-components-switch-thumb-radius)',
        'table-radius': 'var(--theme-components-table-radius)',
        'textarea-radius': 'var(--theme-components-textarea-radius)',
      },
      boxShadow: {
        'card-shadow': 'var(--theme-components-card-shadow)',
        'dialog-shadow': 'var(--theme-components-dialog-shadow)',
        'dropdown-shadow': 'var(--theme-components-dropdown-shadow)',
        'hovercard-shadow': 'var(--theme-components-hovercard-shadow)',
      },
      ringColor: {
        'input-focus-ring': 'var(--theme-components-input-focus-ring)',
        'switch-focus-ring': 'var(--theme-components-switch-focus-ring)',
        'textarea-focus-ring': 'var(--theme-components-textarea-focus-ring)',
      },
      borderColor: {
        'chart-tooltip-border': 'var(--theme-components-chart-tooltip-border)',
        'input-border': 'var(--theme-components-input-border)',
        'sonner-border': 'var(--theme-components-sonner-border)',
        'sonner-loading-border':
          'var(--theme-components-sonner-loading-border)',
        'table-divider': 'var(--theme-components-table-divider)',
        'textarea-border': 'var(--theme-components-textarea-border)',
      },
      width: {
        'switch-thumb-size': 'var(--theme-components-switch-thumb-size)',
        'switch-width': 'var(--theme-components-switch-width)',
      },
      height: {
        'switch-height': 'var(--theme-components-switch-height)',
      },
    },
  },
} satisfies Config
