/**
 * Schema-driven route + client generator.
 *
 * Reads the `Schemas` registry (`.server/schemas`) and emits:
 *
 * 1. `routes/gen/<category>.<group>.tsx` — route modules re-exporting the
 *    group's `middleware`, `action`, and `loader` (when present).
 * 2. `routes/gen/index.ts` — the route tree: public groups at `api/v3/` root,
 *    everything else under the require-auth `api.secure` layout.
 * 3. `lib/executeAction.ts` — a fully-typed client: each entry pairs an
 *    operation with its route path via `clientAction`, so params/body/return
 *    types flow straight from the server `Schemas` object.
 */
import { layout, route } from "@react-router/dev/routes"
import type { SchemaGroupLike } from "../middleware/withValidation"
import { Schemas } from "../schemas"

interface GroupEntry {
  category: string
  group: string
  def: SchemaGroupLike
}

function isSchemaGroupLike(value: unknown): value is SchemaGroupLike {
  if (typeof value !== "object" || value === null) return false
  const v = value as Record<string, unknown>
  return (
    "_ops" in v &&
    typeof v._ops === "object" &&
    "_options" in v &&
    typeof v._options === "object" &&
    "middleware" in v &&
    "action" in v
  )
}

function collectGroups(): GroupEntry[] {
  const entries: GroupEntry[] = []
  for (const [category, groups] of Object.entries(Schemas)) {
    for (const [group, def] of Object.entries(groups)) {
      if (!isSchemaGroupLike(def)) {
        console.log(`Skipping ${category}.${group}: not a schema group`)
        continue
      }
      if (def._options.ignored) {
        console.log(`Skipping ${category}.${group}: ignored`)
        continue
      }
      entries.push({ category, group, def })
      console.log(`Group: ${category}.${group} -> /api/v3/${def._options.path}`)
    }
  }
  return entries
}

function routeFileName(category: string, group: string): string {
  return `${category}.${group}`.toLowerCase()
}

function emitRouteModule(entry: GroupEntry): string {
  const fileName = routeFileName(entry.category, entry.group)
  const hasLoader = typeof entry.def.loader === "function"
  const opKeys = Object.keys(entry.def._ops)
  const accessor = `Schemas.${entry.category}.${entry.group}`

  return `// @generated by .server/scripts/index.ts — do not edit
import { Schemas } from "~/.server/schemas"
import type { Route } from "./+types/${fileName}"

export const middleware: Route.MiddlewareFunction[] = [${accessor}.middleware]

export const action = ${accessor}.action
${hasLoader ? `\nexport const loader = ${accessor}.loader\n` : ""}
/*
  route: /api/v3/${entry.def._options.path}
  operations: ${opKeys.length > 0 ? opKeys.join(", ") : "(none)"}
  isPublic: ${String(Boolean(entry.def._options.isPublic))}
  roles: ${entry.def._options.roles?.join(", ") || "(any authenticated)"}
*/
`
}

function emitRouteTree(entries: GroupEntry[]): string {
  const publicEntries = entries.filter((e) => e.def._options.isPublic)
  const secureEntries = entries.filter((e) => !e.def._options.isPublic)

  const routeLine = (e: GroupEntry, indent: string) =>
    `${indent}route("${e.def._options.path}", "routes/gen/${routeFileName(e.category, e.group)}.tsx")`

  const publicChildren = publicEntries.map((e) => routeLine(e, "      ")).join(",\n")
  const secureChildren = secureEntries.map((e) => routeLine(e, "      ")).join(",\n")

  return `// @generated by .server/scripts/index.ts — do not edit
import { layout, route } from "@react-router/dev/routes"

const GeneratedRoutes = [
  route("api/v3/", "routes/api.tsx", [
    // Public: login/OIDC/revoke — mounted outside the require-auth layout
${publicEntries.length > 0 ? publicChildren : "      // (none)"},
    // Secure: everything behind createRequireAuthMiddleware (mode: "json")
    layout("routes/api.secure.tsx", [
${secureEntries.length > 0 ? secureChildren : "      // (none)"}
    ]),
  ]),
]

export default GeneratedRoutes
`
}

function emitExecuteAction(entries: GroupEntry[]): string {
  const lines: string[] = []
  for (const { category, group, def } of entries) {
    const path = def._options.path
    for (const opKey of Object.keys(def._ops)) {
      lines.push(
        `\t"${category}.${group}.${opKey}": clientAction<
\t\ttypeof Schemas.${category}.${group}["_ops"],
\t\t"${opKey}",
\t\t"${path}"
\t>("${opKey}", "${path}"),`
      )
    }
  }

  return `// @generated by .server/scripts/index.ts — do not edit
import { clientAction } from "~/lib/api"
import type { Schemas } from "~/.server/schemas"

/**
 * Fully-typed API client generated from the server Schemas registry.
 *
 *   executeAction["Auth.ApiKey.revoke"]({ params: { id: "abc" } })
 *   executeAction["Config.Pin.pin"]({ body: { path, slug } })
 *
 * Schemas is imported type-only: types flow from the server registry while
 * the client bundle only contains the clientAction runtime.
 */
export const executeAction = {
${lines.join("\n")}
}
`
}

async function main() {
  const appDir = __dirname.match(/.*\.server/g)?.[0]?.replace(/\/?\.server$/, "") ?? "."
  console.log("App dir:", appDir)

  const write = async (filePath: string, data: string) => {
    console.log("Writing:", filePath)
    await Bun.write(`${appDir}/${filePath}`, data)
  }

  const entries = collectGroups()

  for (const entry of entries) {
    await write(
      `routes/gen/${routeFileName(entry.category, entry.group)}.tsx`,
      emitRouteModule(entry)
    )
  }

  await write("routes/gen/index.ts", emitRouteTree(entries))
  await write("lib/executeAction.ts", emitExecuteAction(entries))

  console.log(`Generated ${entries.length} route modules + route tree + executeAction client.`)
}

await main()
process.exit(0)
